apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user-deployment
  namespace: default
  labels:
    app:  user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  user-deployment
    spec:
      containers:
      - name:  user-deployment
        image:  philipasd/user_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort:  7000
          name:  user-deployment

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: user-deployment
  ports:
  - name: user-service
    protocol: TCP
    port: 80
    targetPort: 7000
  